### ISSUE TITLE
Dragging doesn't works if the pointer leaves the SimpleListboxItem before the dragging start

### ISSUE THREAD

**Issue by ShivanshuKGupta** [holotrek/selectable_draggable_listbox#4]
**Describe the bug**
When we try to drag a SimpleListboxItem dragging doesn't start if the pointer suddenly moves out of its render box or if the pointer moves to the right after dragging.

**To Reproduce**
1. Go to ['Example'](https://github.com/holotrek/selectable_draggable_listbox/blob/main/example/lib/main.dart) and try running it as a Windows App.
2. Press the mouse cursor on any item from the Grocery List and drag it such that the pointer moves only horizontally or moves so fast as to go out of its render box immediately
3. The item won't start dragging

**Expected behavior**
The item should have started dragging

**Screenshots**

**Version (please complete the following information):**
The results of `flutter --version` here:
Flutter 3.22.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision a14f74ff3a (3 days ago) • 2024-05-22 11:08:21 -0500
Engine • revision 55eae6864b
Tools • Dart 3.4.1 • DevTools 2.34.3

**Device (please complete the following information):**
 - OS: Window 10
 - Version: 22H2

**Additional context**
You may see this video here for more details:
https://drive.google.com/file/d/1HbtSe54Nc0K8K0bTx7cr0WKv97k5_WDJ

Here, if I move the cursor a little bit fast then the item will get selected but will not be dragged along.

**Comment by holotrek** [comment]
@ShivanshuKGupta Thanks for your submission. Sorry it took so long to respond. Somehow Github failed to alert me of this issue. I will be deploying a fix soon.

**Comment by ShivanshuKGupta** [comment]
Thanks
